### ISSUE TITLE
Could you please unpublish this?

### ISSUE THREAD

**Issue by mischah** [cirosantilli/all-github-commit-emails#1]
Hi, nice data leak :flushed:

I’m in this list with two of my email adresses and therefore I like to ask you:
Would you be so kind to unpublish that?

I know it’s public data. But extracted in that way it’s a source for massive abuse.
I guess I know now how people and spammers get one of my two email addresses which isn’t published anywhere else on the internet (as far as I know.)

**Comment by cirosantilli** [comment]
I'm sorry, but I think I'll keep this up because:
- more people like you can learn how their emails are being leaked and GitHub might be lead to warn people more clearly that their Git commit emails are public
- to actually mass spam, attackers need to go through larger entry barriers than this (e.g. pay some shady service), so I don't think this will be the limiting factor

I know that the "aggressive hacking" way is can have dangers and cause damage, but when methods are already public knowledge and since "bad guys" are always one step ahead, I think it is better to make it crystal clear what the bad guys know or not.

:wink:
